FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exposition du port standard de Streamlit
EXPOSE 8501

# Commande de démarrage de Streamlit en désactivant le tracking CORS pour Docker
CMD ["streamlit", "run", "crypto_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]