version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: datascientest
      MONGO_INITDB_ROOT_PASSWORD: dst123
    volumes:
      - ./sample_training:/data/db
    ports:
      - 27017:27017
    networks:
      - crypto_network

  db:
    container_name: pg_container
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: datascientest
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network

  # FastAPI Backend API
  api:
    image: diane19/crypto-api:latest
    container_name: crypto_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://daniel:datascientest@db:5432/crypto_db
      - MONGO_URL=mongodb://datascientest:dst123@mongodb:27017/
    volumes:
      - ./crypto_model.joblib:/app/crypto_model.joblib
      - ./crypto_scaler.joblib:/app/crypto_scaler.joblib
    depends_on:
      - db
      - mongodb
    networks:
      - crypto_network

  # Streamlit Frontend Dashboard
  streamlit_ui:
    image: diane19/crypto-streamlit:latest
    container_name: crypto_streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - crypto_network

  # Streaming Data Pipeline
  streaming_pipeline:
    image: diane19/crypto-api:latest
    container_name: crypto_streaming
    restart: always
    command: python streaming.py 
    environment:
      - MONGO_URL=mongodb://datascientest:dst123@mongodb:27017/
      - API_URL=http://api:8000
    volumes:
      - ./crypto_model.joblib:/app/crypto_model.joblib
      - ./crypto_scaler.joblib:/app/crypto_scaler.joblib
    depends_on:
      - mongodb
      - api
    networks:
      - crypto_network

  # Prometheus Metrics Collector
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    networks:
      - crypto_network

  # Grafana Dashboard Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - crypto_network

volumes:
  postgres_data:
  mongo_data:

networks:
  crypto_network:
    driver: bridge